dist: xenial
language: generic
sudo: required
services:
  - docker
branches:
  only:
    - master
before_script:
  - pyflakes *.py cobbler/*.py cobbler/modules/*.py cobbler/web/*.py cobbler/web/templatetags/*.py bin/cobbler* bin/*.py web/cobbler.wsgi
  - pycodestyle -r --ignore E501,E402,E722 *.py cobbler/*.py cobbler/modules/*.py cobbler/web/*.py cobbler/web/templatetags/*.py bin/cobbler* bin/*.py web/cobbler.wsgi
script:
  - docker build -t cobbler .
  - docker run -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --name cobbler cobbler
  - sleep 30
  - docker logs cobbler
  - docker exec -u 0 -it cobbler bash
  - pytest
  - exit
